# Generated by Django 5.0.3 on 2026-06-22 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_alter_documentopostulacion_options'),
        ('modalidades', '0007_historial_cambio_modalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalidadTipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatorio', models.BooleanField(default=False, help_text='Si es True, el documento debe presentarse en esta etapa')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de presentación sugerido')),
                ('descripcion_requerimiento', models.TextField(blank=True, help_text='Especificaciones adicionales para este documento en esta modalidad')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('etapa', models.ForeignKey(blank=True, help_text='Si está vacío, el documento aplica a todas las etapas', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_requeridos', to='modalidades.etapa')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_documento_requeridos', to='modalidades.modalidad')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidades', to='documentos.tipodocumento')),
            ],
            options={
                'verbose_name': 'Modalidad Tipo Documento',
                'verbose_name_plural': 'Modalidades Tipos Documentos',
                'ordering': ['modalidad__nombre', 'orden', 'tipo_documento__nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='modalidadtipodocumento',
            constraint=models.UniqueConstraint(fields=('modalidad', 'tipo_documento', 'etapa'), name='unique_modalidad_documento_etapa'),
        ),
    ]
