# Generated by Django 5.0.3 on 2026-06-17 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0007_historial_cambio_modalidad'),
        ('postulantes', '0008_academic_period_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambioModalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('modalidad_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_cambios_modalidad_anterior', to='modalidades.modalidad')),
                ('modalidad_nueva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_cambios_modalidad_nueva', to='modalidades.modalidad')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios_modalidad', to='postulantes.postulante')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_cambios_modalidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de cambio de modalidad',
                'verbose_name_plural': 'Historiales de cambio de modalidad',
                'ordering': ['-fecha'],
            },
        ),
    ]
