# Generated by Django 5.0.3 on 2026-05-27 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0002_etapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalidadRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='modalidades/requisitos/')),
                ('categoria', models.CharField(blank=True, default='General', max_length=100)),
                ('obligatorio', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='modalidades.modalidad')),
            ],
            options={
                'ordering': ['modalidad__nombre', 'nombre'],
            },
        ),
    ]
