# Generated by Django 5.0.3 on 2026-06-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0006_populate_etapas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modalidadrequisito',
            options={'ordering': ['modalidad__nombre', 'orden', 'nombre']},
        ),
        migrations.AddField(
            model_name='modalidadrequisito',
            name='orden',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
